@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

List <|-- MyList

class ArrayList {
    Object[] elementData
    size()
}

class MyList {
    Object[] myElements
    Integer size
    size() Integer
}


enum TimeUnit {
    DAYS
    HOURS
    MINUTES
}

@enduml